Feature/student list
MJU-ClassmanagementSystem/Client pull request #8
Opened 2023-05-12 12:41 UTC by snowari

# PR

## 🗄️ 종류

PR 종류를 선택하세요

- [ ] Code Review
- [x] New Feature
- [ ] Remove Feature
- [ ] Change Logic
- [ ] Bug Fix
- [ ] Setup

<br>

## 🗜️ 새로 설치한 패키지

-

## 🔍 왜 변경을 했습니까?

- 학생 셀렉터 추가

<br>

## 🔧 작업 내용

- 내용명: 이름 셀렉터를 추가했습니다.

<br>

## 📷 스크린샷
![image](https://github.com/MJU-ClassmanagementSystem/Client/assets/70631889/49ba3691-5f6b-474d-a888-375b1be94995)

<br>

## 📝 리뷰할 때 참고할 점

-

2023-05-12 12:54 UTC, BHyeonKim requested changes
고생하셨습니다👏

2023-05-12 12:54 UTC, BHyeonKim commented on src/components/features/StudentList/index.tsx
> +          className={cx('list', { selected: student.id === selectedID })}
selected라는 클래스는 안쓰이는 것 같은데요?

2023-05-12 12:54 UTC, BHyeonKim commented on src/components/features/StudentList/index.tsx
>  const StudentList = () => {
이름을 props로 받을 수 있도록 해주세요

2023-05-14 12:22 UTC, snowari commented on src/components/features/StudentList/index.tsx
>  const StudentList = () => {
넹~

2023-05-14 12:48 UTC, BHyeonKim approved these changes
고생하셨습니다 👍

2023-05-14 12:53 UTC, merged